### ISSUE TITLE
Custom selection with "locked" status

### ISSUE THREAD

**Issue by rbleuse** [jehutyno/yomikata#2]
Hi,

I'm using Yomikata to get quizzes about pronounciation/pronounciation_qcm on custom selections.

But I'm unable to select **_only_** these 2 quizzes options, because it seems that custom selections are `locked` :

https://github.com/jehutyno/yomikata/blob/c7700bc8298fa807d3622fcf92d984c9345d0b2b/app/src/main/kotlin/com/jehutyno/yomikata/screens/quizzes/QuizzesFragment.kt#L84

```kotlin
fun isCategoryNotLocked(): Boolean {
    return selectedCategory != Categories.CATEGORY_SELECTIONS
}
```

Is there any reason why we can't use custom quizz options on custom selections ? What's the idea with the `locked` status ?

**Comment by jehutyno** [comment]
Hi,
You are right, this lock is not relevant anymore. It's a remnant of the full version lock so the condition can be removed.

**Comment by rbleuse** [comment]
I see, thanks. I pushed a PR to remove this lock
